name: Tests

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
        python-version: ["3.9", "3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install tests dependencies
      run: python -m pip install tox

    - name: run Python tests
      run: tox -e tests
    - uses: codecov/codecov-action@v3
      with:
        files: ./tests/coverage.xml
